In [35]:
import numpy as np

co = np.array([[1,2,3],[4,5,6],[7,8,9]])
re = np.array([[1,2,3],[4,5,6],[7,8,9]])
type((co.T * re.T))
np.reshape(co,(1,9)).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [74]:
a = np.random.randint(1,100,size=[10,3])
print(a)
# 取出0，3行的数据
a[[0,3]]
# 取出第一列的数据
a[:,0:1]
# 取出第0,2列的数据
a[:,[0,2]]
# 取出第1行,2列的数据
a[1,2]

[[36 37  4]
 [92 98 41]
 [ 6 90 64]
 [17  6 99]
 [96 71 12]
 [13 22 84]
 [30 52 48]
 [32  9 66]
 [92 75 17]
 [82 61 70]]


41

In [87]:
# 范围0-1
b = np.random.random((2,3))
# 范围2-300
c = np.random.randint(2,300,size=(2,3))
c

array([[110,  46, 199],
       [ 96, 150, 117]])

In [97]:
jjj = np.array([[1,2,3],[4,5,6],[7,8,9]])
# -1可以自动计算行或列
jjj.reshape(-1,3)
jjj.reshape(3,-1)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
oo = np.zeros([3,3])
oo


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [107]:
np.identity(100)

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [110]:
a = [1,2,3,4,5,6,7,8,9]
np.diag(a)
np.diag(np.diag(a))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
a = np.identity(3)
b = np.array([1,0,0,0,1,0,0,0,1])
np.allclose(a,b.reshape(3,-1))

True

In [144]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]]).T
# np.dot(a,b)
# a*b
np.multiply(a,b)


array([[ 1,  8, 21],
       [ 8, 25, 48],
       [21, 48, 81]])

In [152]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
b = np.mat([[1,2,3],[4,5,6],[7,8,9]])
np.dot(a,b)
a*b

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [194]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1],[2],[3]]).T
c = np.array([[1,34,5]]).T
# np.dot(a,b)
c
np.dot(a,c)

array([[ 84],
       [204]])

In [200]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
a**3
np.power(a,3)

matrix([[  1,   8,  27],
        [ 64, 125, 216],
        [343, 512, 729]], dtype=int32)

In [214]:
A = np.array([[1, 2], [3, 4]])
n = 2

# 矩阵的乘方
A_n = np.linalg.matrix_power(A, n)
np.mat(A)**n
print("矩阵的乘方 A^2:\n", A_n)
np.mat(A)**n


A**2
np.power(A,2)

矩阵的乘方 A^2:
 [[ 7 10]
 [15 22]]


array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [1]:
a = np.mat([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
a.I

NameError: name 'np' is not defined

In [21]:

import numpy as np

n = 3  # 矩阵尺寸

# 生成随机矩阵

matrix = np.random.rand(n, n)

# 生成对称矩阵

a = (matrix + matrix.T) / 2
type(a == a.T)
a == a.T

# 生成逆矩阵
np.mat(a).I


matrix([[ 3.20249407,  1.1192169 , -4.65888391],
        [ 1.1192169 ,  3.5711417 , -4.50415283],
        [-4.65888391, -4.50415283, 11.74740878]])

In [49]:
a = np.array([
    [1, -4, 0, 2],
    [-1, 2, -1,-1],
    [1, -2, 3, 5],
    [2, -6, 1 ,3]
])
b = np.zeros((3,3))
a
np.dot(np.linalg.inv(a),a.T)


LinAlgError: Singular matrix

In [54]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a
np.linalg.det(a)

-9.51619735392994e-16

In [63]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
v3 = np.array([7, 8, 9])

# 将向量作为矩阵的列
matrix = np.column_stack((v1, v2, v3))
matrix
det = np.linalg.det(matrix)
det
rank = np.linalg.matrix_rank(matrix)
matrix.shape[1]

3

In [70]:
import numpy as np

# 定义一个矩阵
matrix = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [3, 2, 1]
])

# 计算矩阵的秩
rank = np.linalg.matrix_rank(matrix)

print("矩阵：")
print(matrix)
print("\n矩阵的秩：", rank)

矩阵：
[[1 2 3]
 [2 4 6]
 [3 2 1]]

矩阵的秩： 2


In [79]:
a = np.array([[1,2,3]])
b = np.array([[4,5,6]])
np.dot(a.T,b)
np.linalg.norm(b)

8.774964387392123

In [91]:
import numpy as np

a = np.array([1, 1, 1])
b = np.array([2, -4, 2])
d = np.array([-1, 0, 1])

c = np.cross(a, b)


np.dot(b.T, c)

0

In [96]:
import numpy as np

# 定义旋转角度 (以弧度为单位)
theta = np.pi / 4  # 45度

# 生成二维旋转矩阵
Q = np.array([
    [np.cos(theta), -np.sin(theta)],
    [np.sin(theta), np.cos(theta)]
])

# 计算 Q 的转置
Q_T = Q.T

# 计算 Q^T Q
result = np.dot(Q_T, Q)

print("Q:")
print(Q)
print("\nQ^T:")
print(Q_T)
print("\nQ^T Q:")
print(result)

Q:
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

Q^T:
[[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Q^T Q:
[[ 1.00000000e+00 -4.26642159e-17]
 [-4.26642159e-17  1.00000000e+00]]


In [1]:
S = np.array([[8.5,9],[4.5,4],[33,1]]) #行商店 列水果的 价格
H = np.array([[8,3,4],[3,4,5]]) #行水果列人员 购买数
T = np.array([[1000,2000],[2000,3000]])#行人员 列城镇 购买数
# 每个人在各个商店消费金额
np.dot(H,S)
# 每个城镇购买数量
np.dot(T,S)

NameError: name 'np' is not defined

In [5]:
from sklearn.datasets import load_iris
data = load_iris()



In [16]:
import sympy as sp
from sympy import *

x , y, z ,w = symbols('x y z w')
eq = [x+y+z-2,x+2*y+4*z-3,x+3*y+9*z-5]
res = solve(eq, x, y, z)
res

{x: 2, y: -1/2, z: 1/2}

In [17]:
import numpy as np
data.data
mt = np.mat(data.data)
mt

matrix([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [33]:
A = np.random.randint(1,20,(3,4))
B = np.random.randint(1,20,(4,5))
Mat_a = np.mat(A)
Mat_b = np.mat(B)
np.linalg.matrix_rank(A)
np.dot(A,B)

array([[388, 332, 297, 350, 540],
       [377, 372, 300, 240, 508],
       [611, 709, 519, 499, 771]])

In [41]:
asd = np.array([[1,2,3],[2,2,1],[3,4,3]])
np.linalg.det(asd)
if np.linalg.det(asd) != 0:
    np.mat(asd).T
np.mat(asd).T

matrix([[1, 2, 3],
        [2, 2, 4],
        [3, 1, 3]])

In [104]:
op = np.random.uniform(1,20,(4,4))
op

ssj = np.triu(op,k=1)
ssj
xsj = np.tril(op,k=1)
xsj
np.fill_diagonal(ssj,xsj)
print(np.diag(op))
np.diag(np.diag(op))
#可以根据矩阵加装置，然后减去对角线元素
a = op + op.T - np.diag(np.diag(op))
print(a)
#可以根据上三角或下三角，分别求装置相加而得
b = xsj + xsj.T
print(b)
b == b.T


SyntaxError: invalid character '，' (U+FF0C) (3507619712.py, line 11)

In [113]:
zero = np.zeros((3,3))
np.identity(4)
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [1]:
a = np.array([[-1,0,1],[1,2,0],[-4,0,3]])
vel ,vex = np.linalg.eig(a)
np.dot(a,vex) == vel*vex
np.allclose(np.dot(a,vex),vel*vex)

NameError: name 'np' is not defined

In [3]:
import numpy as np

# 定义矩阵 A
A = np.array([[4, 1], [2, 3]])

# 使用 numpy.linalg.eig 进行特征值分解
eigenvalues, eigenvectors = np.linalg.eig(A)

# 打印特征值和特征向量
print("特征值 (Eigenvalues):")
print(eigenvalues)
print("\n特征向量 (Eigenvectors):")
print(eigenvectors)

# 验证特征值分解
# 构造对角矩阵 D
D = np.diag(eigenvalues)

# 验证 A = PDP^-1
P = eigenvectors
P_inv = np.linalg.inv(P)

# 计算 PDP^-1
A_reconstructed = P @ D @ P_inv

print("\n重构的矩阵 A:")
print(A_reconstructed)

特征值 (Eigenvalues):
[5. 2.]

特征向量 (Eigenvectors):
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

重构的矩阵 A:
[[4. 1.]
 [2. 3.]]


In [2]:
import numpy as np

# 定义矩阵 A
A = np.array([[1, 2], [3, 4], [5, 6]])

# 使用 numpy.linalg.svd 进行 SVD 分解
U, S, VT = np.linalg.svd(A, full_matrices=True)

# 打印结果
print("矩阵 A:")
print(A)
print("\n左奇异向量矩阵 U:a")
print(U)
print("\n奇异值矩阵 Σ（对角线元素）:")
print(S)
print("\n右奇异向量矩阵 V^T:")
print(VT)

# 验证 SVD 分解
# 构造对角矩阵 Σ
Sigma = np.zeros(A.shape)
np.fill_diagonal(Sigma, S)

# 重构矩阵 A
A_reconstructed = U.dot(Sigma @ VT.T)

print("\n重构的矩阵 A:")
print(A_reconstructed)

矩阵 A:
[[1 2]
 [3 4]
 [5 6]]

左奇异向量矩阵 U:
[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]

奇异值矩阵 Σ（对角线元素）:
[9.52551809 0.51430058]

右奇异向量矩阵 V^T:
[[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]

重构的矩阵 A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [48]:
import numpy as np

A = np.array([[1,1],[1,1],[0,0]])
left_B = A.dot(A.T)
right_B = A.T.dot(A)
left_B_vel, left_B_vex = np.linalg.eig(left_B)
right_B_vel, right_B_vex = np.linalg.eig(right_B)
diag_A = np.diag(A)

singular_values = np.sqrt(np.sort(np.abs(left_B_vel))[::-1])

# 构建奇异值矩阵 Sigma
m, n = A.shape
Sigma = np.zeros((m, n))

np.fill_diagonal(Sigma, singular_values[:min(m, n)])
print(Sigma)


print("左奇异矩阵的特征向量和特征值\n",left_B_vel, "\n", left_B_vex)
print("右奇异矩阵的特征向量和特征值\n",right_B_vel, "\n", right_B_vex)
print("对角元素：\n",diag_A)

left_B_vex.dot(Sigma.dot(right_B_vex.T))

[[2.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.10734243e-08]
 [0.00000000e+00 0.00000000e+00]]
左奇异矩阵的特征向量和特征值
 [4.0000000e+00 4.4408921e-16 0.0000000e+00] 
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]
右奇异矩阵的特征向量和特征值
 [4.0000000e+00 4.4408921e-16] 
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
对角元素：
 [1 1]


array([[1.00000001, 0.99999999],
       [0.99999999, 1.00000001],
       [0.        , 0.        ]])

In [80]:
A = np.array([[1,1],[1,1],[0,0]])
U, S, UT = np.linalg.svd(A)
Sigma = np.zeros(A.shape)
np.fill_diagonal(Sigma, S)
U.dot(Sigma.dot(UT))

array([[1., 1.],
       [1., 1.],
       [0., 0.]])

In [79]:
import numpy as np

# 定义原始矩阵 A
A = np.array([[45, 55], [46, 13], [5, 8]])

# 进行奇异值分解
U, S, VT = np.linalg.svd(A)

# 定义 k 值，这里假设 k = 1
k = 2
# 只保留前 k 个奇异值
S_k = S[:k]

# 只保留 U 矩阵的前 k 列
U_k = U[:, :k]

# 只保留 VT 矩阵的前 k 行
VT_k = VT[:k, :]

# 构建只包含前 k 个奇异值的对角矩阵 Sigma_k
Sigma_k = np.zeros((U_k.shape[1], VT_k.shape[0]))
np.fill_diagonal(Sigma_k, S_k)

# 重构相似矩阵 A_k
A_k = U_k.dot(Sigma_k).dot(VT_k)

print("原始矩阵 A:\n", A)
print("根据前 {} 个奇异值重构的相似矩阵 A_k:\n".format(k), A_k)

原始矩阵 A:
 [[45 55]
 [46 13]
 [ 5  8]]
根据前 2 个奇异值重构的相似矩阵 A_k:
 [[45. 55.]
 [46. 13.]
 [ 5.  8.]]
